import { test, expect } from './app'

test('slash templates combine custom and built-ins, preserve text, and dismiss', async ({ ux }) => {
  await ux.page.evaluate(async () => {
    await window.gt.settings.patch({
      noteTemplates: [{ id: 'custom:daily', title: 'Daily standup', body: '## Local standup' }],
    })
  })
  await ux.openTab('notes')
  const pane = ux.page.locator('[data-tab-pane="notes"]')
  await pane.getByRole('button', { name: 'Scratch', exact: true }).click()
  const editor = pane.locator('.cm-content').locator('visible=true').first()
  await editor.fill('Keep this note')
  await editor.press('Control+End')
  await ux.page.keyboard.type(' /')
  const picker = pane.getByRole('region', { name: 'Slash note templates' })
  await expect(picker.getByRole('button', { name: 'Checklist', exact: true })).toBeVisible()
  await expect(picker.getByRole('button', { name: 'Daily standup · local' })).toBeVisible()
  await ux.page.keyboard.type('dly')
  await expect(picker.getByRole('button')).toHaveCount(1)
  await ux.page.keyboard.press('Enter')
  await expect(editor).toContainText('Keep this note')
  await expect(editor).toContainText('## Local standup')
  await expect(editor).not.toContainText('/dly')
  await ux.page.keyboard.type(' /')
  await expect(picker).toBeVisible()
  await ux.page.keyboard.press('Escape')
  await expect(picker).toHaveCount(0)
  await ux.page.keyboard.type('m')
  await expect(picker).toBeVisible()
  await pane.getByText('Knowledge Base', { exact: true }).click()
  await expect(picker).toHaveCount(0)

  await pane.getByRole('button', { name: 'Path notes', exact: true }).click()
  await pane.getByLabel('Note path', { exact: true }).fill('src/slash.ts')
  await pane.getByRole('button', { name: 'Open path' }).click()
  const pathNote = pane.getByLabel('Path note content')
  await pathNote.fill('Existing path note /mtg')
  await picker.getByRole('button', { name: 'Meeting', exact: true }).click()
  await expect(pathNote).toHaveValue(/Existing path note \n\n## Meeting/)
  await pane.getByRole('button', { name: 'Save note', exact: true }).click()
  await expect(pane.getByRole('status')).toContainText('Saved locally')
  expect(await ux.failures.rejections()).toEqual([])
})
