import { describe, expect, it } from 'bun:test'
import {
  chatSupportsEngine,
  claudeMessages,
  codexMessages,
  sessionMessages,
  type ChatMessage,
} from './messages'

const jsonl = (...objs: unknown[]) => objs.map((o) => JSON.stringify(o)).join('\n') + '\n'
const kinds = (ms: ChatMessage[]) => ms.map((m) => m.kind)
const texts = (ms: ChatMessage[]) =>
  ms.flatMap((m) => (m.kind === 'user' || m.kind === 'assistant' ? [m.text] : []))

describe('claudeMessages', () => {
  it('extracts the conversation and drops transcript bookkeeping', () => {
    const raw = jsonl(
      { type: 'mode', mode: 'normal' },
      { type: 'permission-mode', permissionMode: 'auto' },
      { type: 'ai-title', aiTitle: 'Review open pull request' },
      { type: 'file-history-snapshot', snapshot: {} },
      {
        type: 'user',
        timestamp: '2026-07-21T10:00:00Z',
        message: { role: 'user', content: 'okay see our open PR?' },
      },
      {
        type: 'assistant',
        timestamp: '2026-07-21T10:00:05Z',
        message: { role: 'assistant', content: [{ type: 'text', text: 'Looking now.' }] },
      },
    )
    const out = claudeMessages(raw)
    expect(kinds(out)).toEqual(['user', 'assistant'])
    expect(texts(out)).toEqual(['okay see our open PR?', 'Looking now.'])
  })

  it('turns tool_use blocks into collapsed tool rows', () => {
    const raw = jsonl({
      type: 'assistant',
      timestamp: '2026-07-21T10:00:05Z',
      message: {
        role: 'assistant',
        content: [
          { type: 'text', text: 'Running the suite.' },
          { type: 'tool_use', name: 'Bash', id: 't1', input: { command: 'bun test' } },
        ],
      },
    })
    const out = claudeMessages(raw)
    expect(kinds(out)).toEqual(['assistant', 'tool'])
    const tool = out[1]
    expect(tool.kind === 'tool' && tool.name).toBe('Bash')
    expect(tool.kind === 'tool' && tool.summary).toBe('bun test')
  })

  it('excludes sub-agent chatter, which belongs to its own thread', () => {
    const raw = jsonl(
      {
        type: 'assistant',
        isSidechain: true,
        message: { role: 'assistant', content: [{ type: 'text', text: 'subagent noise' }] },
      },
      {
        type: 'assistant',
        message: { role: 'assistant', content: [{ type: 'text', text: 'real answer' }] },
      },
    )
    expect(texts(claudeMessages(raw))).toEqual(['real answer'])
  })

  it('drops tool-result user lines, which the tool row already covers', () => {
    const raw = jsonl({
      type: 'user',
      message: {
        role: 'user',
        content: [{ type: 'tool_result', tool_use_id: 't1', content: 'exit 0' }],
      },
    })
    expect(claudeMessages(raw)).toEqual([])
  })

  it('survives a truncated trailing line', () => {
    const raw =
      jsonl({
        type: 'user',
        message: { role: 'user', content: 'hi' },
      }) + '{"type":"assist'
    expect(texts(claudeMessages(raw))).toEqual(['hi'])
  })

  it('keeps an interruption as a notice, not as something a human said', () => {
    const raw = jsonl({
      type: 'user',
      message: { role: 'user', content: '[Request interrupted by user]' },
    })
    const out = claudeMessages(raw)
    expect(kinds(out)).toEqual(['notice'])
    expect(out[0].kind === 'notice' && out[0].text).toBe('Request interrupted by user')
  })

  it('drops Claude Code control text that is not conversation', () => {
    // Seen verbatim in real transcripts; rendering these as chat makes it look
    // like the agent or the human said things they never said.
    const raw = jsonl(
      { type: 'assistant', message: { role: 'assistant', content: 'No response requested.' } },
      {
        type: 'user',
        message: {
          role: 'user',
          content: 'Caveat: The messages below were generated by the user while running commands',
        },
      },
      { type: 'user', message: { role: 'user', content: '<command-name>/review</command-name>' } },
      { type: 'user', message: { role: 'user', content: '<local-command-stdout>ok' } },
      { type: 'assistant', message: { role: 'assistant', content: 'a real answer' } },
    )
    expect(texts(claudeMessages(raw))).toEqual(['a real answer'])
  })

  it('is empty, not throwing, for an empty transcript', () => {
    expect(claudeMessages('')).toEqual([])
  })
})

describe('codexMessages', () => {
  it('extracts user and assistant messages, ignoring the developer preamble', () => {
    const raw = jsonl(
      { type: 'session_meta', payload: { id: 'x' } },
      {
        type: 'response_item',
        timestamp: '2026-07-21T10:00:00Z',
        payload: {
          type: 'message',
          role: 'developer',
          content: [{ type: 'input_text', text: '<permissions instructions>' }],
        },
      },
      {
        type: 'response_item',
        timestamp: '2026-07-21T10:00:01Z',
        payload: {
          type: 'message',
          role: 'user',
          content: [{ type: 'input_text', text: 'run the tests' }],
        },
      },
      {
        type: 'response_item',
        timestamp: '2026-07-21T10:00:09Z',
        payload: {
          type: 'message',
          role: 'assistant',
          content: [{ type: 'output_text', text: 'All green.' }],
        },
      },
    )
    const out = codexMessages(raw)
    expect(kinds(out)).toEqual(['user', 'assistant'])
    expect(texts(out)).toEqual(['run the tests', 'All green.'])
  })

  it('pairs a function call with its output to resolve status', () => {
    const raw = jsonl(
      {
        type: 'response_item',
        payload: {
          type: 'function_call',
          call_id: 'c1',
          name: 'exec_command',
          arguments: JSON.stringify({ cmd: 'bun test' }),
        },
      },
      {
        type: 'response_item',
        payload: {
          type: 'function_call_output',
          call_id: 'c1',
          output: 'Process exited with code 0\nok',
        },
      },
    )
    const out = codexMessages(raw)
    expect(out).toHaveLength(1)
    expect(out[0].kind === 'tool' && out[0].name).toBe('exec_command')
    expect(out[0].kind === 'tool' && out[0].summary).toBe('bun test')
    expect(out[0].kind === 'tool' && out[0].status).toBe('ok')
  })

  it('marks a failed tool call as an error', () => {
    const raw = jsonl(
      {
        type: 'response_item',
        payload: { type: 'custom_tool_call', call_id: 'c2', name: 'apply_patch', input: 'patch' },
      },
      {
        type: 'response_item',
        payload: {
          type: 'custom_tool_call_output',
          call_id: 'c2',
          output: 'apply_patch verification failed: could not find lines',
        },
      },
    )
    const out = codexMessages(raw)
    expect(out[0].kind === 'tool' && out[0].status).toBe('error')
  })

  it('leaves a call with no output marked running', () => {
    const raw = jsonl({
      type: 'response_item',
      payload: { type: 'function_call', call_id: 'c3', name: 'exec_command', arguments: '{}' },
    })
    expect(codexMessages(raw)[0].kind === 'tool' && codexMessages(raw)[0]).toMatchObject({
      status: 'running',
    })
  })

  it('drops the injected AGENTS.md context, which no human typed', () => {
    const raw = jsonl(
      {
        type: 'response_item',
        payload: {
          type: 'message',
          role: 'user',
          content: [
            {
              text: '# AGENTS.md instructions for /repo\n\n<INSTRUCTIONS>\nbe good\n</INSTRUCTIONS>',
            },
          ],
        },
      },
      {
        type: 'response_item',
        payload: { type: 'message', role: 'user', content: [{ text: '/code-review PR 116' }] },
      },
    )
    expect(texts(codexMessages(raw))).toEqual(['/code-review PR 116'])
  })

  it('ignores reasoning and tool-search noise', () => {
    const raw = jsonl(
      { type: 'response_item', payload: { type: 'reasoning', encrypted_content: 'zzz' } },
      { type: 'response_item', payload: { type: 'tool_search_call', call_id: 'c4' } },
      { type: 'response_item', payload: { type: 'tool_search_output', call_id: 'c4', tools: [] } },
    )
    expect(codexMessages(raw)).toEqual([])
  })

  it('survives a truncated trailing line', () => {
    const raw =
      jsonl({
        type: 'response_item',
        payload: { type: 'message', role: 'user', content: [{ text: 'hi' }] },
      }) + '{"type":"resp'
    expect(texts(codexMessages(raw))).toEqual(['hi'])
  })
})

describe('sessionMessages', () => {
  it('reports engines with no adapter as unsupported rather than empty', () => {
    const out = sessionMessages('whatever', 'cursor')
    expect(out.unsupported).toBe(true)
    expect(out.messages).toEqual([])
  })

  it('treats a supported engine with no transcript as empty, not unsupported', () => {
    const out = sessionMessages('no-such-session-id', 'claude')
    expect(out.unsupported).toBe(false)
    expect(out.messages).toEqual([])
  })

  it('refuses a traversing session id', () => {
    expect(sessionMessages('../../etc/passwd', 'claude').messages).toEqual([])
    expect(sessionMessages('a/b', 'codex').messages).toEqual([])
  })

  it('knows which engines it can render', () => {
    expect(chatSupportsEngine('claude')).toBe(true)
    expect(chatSupportsEngine('codex')).toBe(true)
    expect(chatSupportsEngine('cursor')).toBe(false)
  })
})
