import type {
  PrAggregates,
  PrClassTotals,
  PrDirTotal,
  PrFileChange,
  PrFileClass,
  PrFileStatus,
  PrOverview,
  PrTypeTotal,
} from './types/mrs'

// The pre-diff read for a PR: parse the unified diff, classify each file, and
// aggregate twice — once over everything, once with the noise removed.
//
// The point is attention. A 4,000-line PR that is 3,900 lines of bun.lock is a
// 100-line PR, and a reviewer who does not know that either reads the lockfile
// or skims the part that mattered. So classification is not decoration here: it
// is the only thing standing between the reviewer and a wrong first impression.
//
// Everything is derived from the diff text. No forge call, no filesystem, no
// model — which is what lets this render instantly when a PR is selected.
//
// NON-GOAL: formatting-only detection. Telling "reindented" from "rewritten"
// needs a language-aware re-parse of both sides of every hunk (or a whitespace-
// insensitive re-diff per file), which costs far more than the rest of this
// module combined and is wrong on exactly the languages where whitespace is
// semantic. Prettier churn therefore reads as ordinary source churn.

// ── Classification ───────────────────────────────────────────────────────────

export type ClassRule = {
  /** Stable id, surfaced on the file so a surprising class is debuggable. */
  id: string
  cls: PrFileClass
  match: (path: string, parts: { base: string; segs: string[]; ext: string }) => boolean
}

const NOISE_CLASSES: PrFileClass[] = ['lockfile', 'generated', 'vendored', 'snapshot']

const LOCKFILES = new Set([
  'bun.lock',
  'bun.lockb',
  'package-lock.json',
  'npm-shrinkwrap.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'cargo.lock',
  'poetry.lock',
  'uv.lock',
  'pipfile.lock',
  'gemfile.lock',
  'composer.lock',
  'go.sum',
  'flake.lock',
  'packages.lock.json',
])

const VENDOR_SEGS = new Set(['vendor', 'vendored', 'node_modules', 'third_party', 'thirdparty'])

const TEST_SEGS = new Set(['test', 'tests', '__tests__', 'spec', 'e2e'])

/**
 * Committed build output and regen targets. These are files the repo's own
 * regen/build conventions rewrite wholesale, so reviewing their diff reviews a
 * generator's output rather than anyone's decision.
 *
 * Path prefixes, not globs — a repo that adds a regen target adds a line here.
 */
const GENERATED_PATHS = [
  'src/main/ipc-channels.ts', // regenerated by src/main/ipc-channels.gen.ts
  'bin/terminal-cron', // built artifact, checked in
  'out/',
  'dist/',
  'build/',
  'coverage/',
  '.next/',
]

/**
 * Ordered. First match wins, and the order is a decision: a lockfile inside a
 * vendored tree is still a lockfile, and a snapshot is noise before it is a test.
 */
export const CLASS_RULES: ClassRule[] = [
  { id: 'lockfile-name', cls: 'lockfile', match: (_p, { base }) => LOCKFILES.has(base) },
  {
    id: 'vendored-dir',
    cls: 'vendored',
    match: (_p, { segs }) => segs.some((s) => VENDOR_SEGS.has(s)),
  },
  {
    id: 'snapshot',
    cls: 'snapshot',
    match: (_p, { segs, ext }) => ext === 'snap' || segs.includes('__snapshots__'),
  },
  {
    id: 'generated-path',
    cls: 'generated',
    match: (p) => GENERATED_PATHS.some((g) => (g.endsWith('/') ? p.startsWith(g) : p === g)),
  },
  {
    id: 'generated-name',
    cls: 'generated',
    match: (_p, { base }) => /\.(gen|generated|pb|pb2)\./.test(base) || /_pb2?\./.test(base),
  },
  {
    id: 'test-path',
    cls: 'test',
    match: (_p, { base, segs }) =>
      /\.(test|spec)\./.test(base) || segs.slice(0, -1).some((s) => TEST_SEGS.has(s)),
  },
  {
    id: 'docs-path',
    cls: 'docs',
    match: (_p, { segs, ext }) =>
      ['md', 'mdx', 'rst', 'adoc', 'txt'].includes(ext) || segs.slice(0, -1).includes('docs'),
  },
]

/** Classify a path. Pure, order-sensitive, and the same function main and the
 *  renderer use — there is exactly one answer for a given path. */
export function classifyPath(path: string): { cls: PrFileClass; rule: string; noise: boolean } {
  const segs = path.split('/').filter(Boolean)
  const base = (segs[segs.length - 1] || path).toLowerCase()
  const dot = base.lastIndexOf('.')
  const ext = dot > 0 ? base.slice(dot + 1) : ''
  for (const rule of CLASS_RULES) {
    if (rule.match(path, { base, segs, ext })) {
      return { cls: rule.cls, rule: rule.id, noise: NOISE_CLASSES.includes(rule.cls) }
    }
  }
  return { cls: 'source', rule: 'default', noise: false }
}

/** How many added lines the generated-header sniff reads. A generator's banner
 *  is line 1-3 of the file; scanning further would make this a content scan. */
const HEADER_SNIFF_LINES = 5
const GENERATED_HEADER = /@generated|GENERATED by|DO NOT EDIT|Code generated by/i

// ── File type groups ─────────────────────────────────────────────────────────

const TYPE_GROUPS: { id: string; exts: string[] }[] = [
  { id: 'ts', exts: ['ts', 'tsx', 'js', 'jsx', 'mjs', 'cjs'] },
  { id: 'md', exts: ['md', 'mdx'] },
  { id: 'data', exts: ['json', 'yaml', 'yml', 'toml'] },
  { id: 'css', exts: ['css', 'scss', 'sass', 'less'] },
  { id: 'sh', exts: ['sh', 'bash', 'zsh'] },
]

function typeGroup(path: string): string {
  const base = path.split('/').pop() || path
  const dot = base.lastIndexOf('.')
  const ext = dot > 0 ? base.slice(dot + 1).toLowerCase() : ''
  return TYPE_GROUPS.find((g) => g.exts.includes(ext))?.id || 'other'
}

// ── Parsing ──────────────────────────────────────────────────────────────────

const stripPrefix = (p: string): string => p.replace(/^"|"$/g, '').replace(/^[ab]\//, '')

type ParsedFile = PrFileChange & { addedHead: string[]; addedText: string }

function parseFileBlock(lines: string[]): ParsedFile | null {
  const header = lines[0] || ''
  const git = header.match(/^diff --git (.+) (.+)$/)
  if (!git) return null

  let oldPath = stripPrefix(git[1])
  let newPath = stripPrefix(git[2])
  let status: PrFileStatus = 'mod'
  let binary = false
  let adds = 0
  let dels = 0
  let inHunk = false
  const addedHead: string[] = []
  const addedBody: string[] = []

  for (const line of lines.slice(1)) {
    if (line.startsWith('@@')) {
      inHunk = true
      continue
    }
    if (!inHunk) {
      if (line.startsWith('new file mode')) status = 'add'
      else if (line.startsWith('deleted file mode')) status = 'del'
      else if (line.startsWith('rename from ')) {
        status = 'rename'
        oldPath = stripPrefix(line.slice('rename from '.length))
      } else if (line.startsWith('rename to ')) {
        status = 'rename'
        newPath = stripPrefix(line.slice('rename to '.length))
      } else if (/^Binary files .* differ$/.test(line) || line.startsWith('GIT binary patch')) {
        binary = true
      } else if (line.startsWith('--- ')) {
        const p = line.slice(4).trim()
        if (p !== '/dev/null') oldPath = stripPrefix(p)
      } else if (line.startsWith('+++ ')) {
        const p = line.slice(4).trim()
        if (p !== '/dev/null') newPath = stripPrefix(p)
      }
      continue
    }
    if (line.startsWith('+')) {
      adds++
      const text = line.slice(1)
      if (addedHead.length < HEADER_SNIFF_LINES) addedHead.push(text)
      addedBody.push(text)
    } else if (line.startsWith('-')) {
      dels++
    }
  }

  // `path` is what the file IS now; a deletion has no new path, so it keeps the
  // old one rather than rendering as an empty row.
  const path = status === 'del' ? oldPath : newPath || oldPath
  const cls = classifyPath(path)
  const sniffed =
    cls.rule === 'default' && addedHead.some((l) => GENERATED_HEADER.test(l))
      ? { cls: 'generated' as PrFileClass, rule: 'generated-header', noise: true }
      : cls
  return {
    path,
    ...(status === 'rename' && oldPath !== path ? { oldPath } : {}),
    adds,
    dels,
    status,
    binary,
    cls: sniffed.cls,
    rule: sniffed.rule,
    noise: sniffed.noise,
    addedHead,
    addedText: addedBody.join('\n'),
  }
}

function splitFileBlocks(diff: string): string[][] {
  const out: string[][] = []
  let cur: string[] | null = null
  for (const line of diff.split('\n')) {
    if (line.startsWith('diff --git ')) {
      if (cur) out.push(cur)
      cur = [line]
    } else if (cur) {
      cur.push(line)
    }
  }
  if (cur) out.push(cur)
  return out
}

// ── Aggregation ──────────────────────────────────────────────────────────────

const ALL_CLASSES: PrFileClass[] = [
  'source',
  'test',
  'docs',
  'lockfile',
  'generated',
  'vendored',
  'snapshot',
]

const zero = (): PrClassTotals => ({ files: 0, adds: 0, dels: 0 })

function emptyByClass(): Record<PrFileClass, PrClassTotals> {
  return Object.fromEntries(ALL_CLASSES.map((c) => [c, zero()])) as Record<
    PrFileClass,
    PrClassTotals
  >
}

const churn = (t: { adds: number; dels: number }): number => t.adds + t.dels

const add = (into: PrClassTotals, f: PrFileChange): void => {
  into.files += 1
  into.adds += f.adds
  into.dels += f.dels
}

function aggregate(files: PrFileChange[]): PrAggregates {
  const byClass = emptyByClass()
  const types = new Map<string, PrTypeTotal>()
  const dirs = new Map<string, PrDirTotal>()
  let adds = 0
  let dels = 0
  let renames = 0
  let binaries = 0

  for (const f of files) {
    adds += f.adds
    dels += f.dels
    if (f.status === 'rename') renames++
    if (f.binary) binaries++
    add(byClass[f.cls], f)

    const tid = typeGroup(f.path)
    const t = types.get(tid) || { id: tid, ...zero() }
    add(t, f)
    types.set(tid, t)

    const segs = f.path.split('/').filter(Boolean)
    // A root-level file rolls into '.', not into an invented directory.
    const keys: [string, 1 | 2][] = segs.length < 2 ? [['.', 1]] : [[segs[0], 1]]
    if (segs.length > 2) keys.push([`${segs[0]}/${segs[1]}`, 2])
    for (const [path, depth] of keys) {
      const d = dirs.get(path) || { path, depth, ...zero() }
      add(d, f)
      dirs.set(path, d)
    }
  }

  const testChurn = churn(byClass.test)
  const sourceChurn = churn(byClass.source)

  return {
    files: files.length,
    adds,
    dels,
    renames,
    binaries,
    byClass,
    byFileType: [...types.values()].sort((a, b) => churn(b) - churn(a)),
    byDirectory: [...dirs.values()].sort((a, b) => a.depth - b.depth || churn(b) - churn(a)),
    testRatio: testChurn + sourceChurn === 0 ? null : testChurn / (testChurn + sourceChurn),
    largest: [...files]
      .sort((a, b) => churn(b) - churn(a))
      .slice(0, 5)
      .map((f) => ({ path: f.path, cls: f.cls, files: 1, adds: f.adds, dels: f.dels })),
  }
}

// ── Hints ────────────────────────────────────────────────────────────────────

const SPAWN_CALL = /\b(spawn|spawnSync|exec|execSync|execFile|execFileSync|fork)\s*\(/

const plural = (n: number, word: string): string => `${n} ${word}${n === 1 ? '' : 's'}`

function hintsFor(files: ParsedFile[], filtered: PrAggregates): string[] {
  const out: string[] = []

  const deletedTests = files.filter((f) => f.cls === 'test' && f.status === 'del')
  if (deletedTests.length > 0) out.push(`Deletes ${plural(deletedTests.length, 'test file')}`)

  const sourceFiles = filtered.byClass.source.files
  if (sourceFiles > 0 && churn(filtered.byClass.test) === 0) {
    out.push(`No test changes alongside ${plural(sourceFiles, 'source file')}`)
  }

  const spawners = files.filter(
    (f) => f.path.startsWith('src/main/') && SPAWN_CALL.test(f.addedText),
  )
  if (spawners.length > 0) {
    out.push(`Adds process spawn/exec calls in ${plural(spawners.length, 'main-process file')}`)
  }

  // "One file is most of this" is only useful once the change is big enough
  // that a reviewer would have budgeted time for it; on a 30-line PR it is a
  // truism that fires on almost every diff.
  const DOMINANT_MIN_CHURN = 200
  const total = filtered.adds + filtered.dels
  const top = filtered.largest[0]
  if (top && total >= DOMINANT_MIN_CHURN && churn(top) / total >= 0.6 && filtered.files > 1) {
    out.push(`${top.path} is ${Math.round((churn(top) / total) * 100)}% of the reviewable change`)
  }

  const bins = files.filter((f) => f.binary)
  if (bins.length > 0) out.push(`${plural(bins.length, 'binary file')} cannot be reviewed as text`)

  return out
}

// ── Entry point ──────────────────────────────────────────────────────────────

export const EMPTY_PR_OVERVIEW: PrOverview = {
  files: [],
  raw: aggregate([]),
  filtered: aggregate([]),
  noise: { ...zero(), byClass: emptyByClass() },
  hints: [],
}

/** Parse a unified diff into the reviewer's pre-diff read. Safe on garbage
 *  input: anything that is not a diff yields the empty overview. */
export function analyzePrDiff(diff: string): PrOverview {
  const parsed = splitFileBlocks(diff || '')
    .map(parseFileBlock)
    .filter((f): f is ParsedFile => f !== null && !!f.path)
  if (parsed.length === 0) return EMPTY_PR_OVERVIEW

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const files: PrFileChange[] = parsed.map(({ addedHead, addedText, ...f }) => f)
  const filteredFiles = files.filter((f) => !f.noise)
  const noiseFiles = files.filter((f) => f.noise)

  const noiseByClass = emptyByClass()
  const noise = { ...zero(), byClass: noiseByClass }
  for (const f of noiseFiles) {
    add(noise, f)
    add(noiseByClass[f.cls], f)
  }

  const filtered = aggregate(filteredFiles)
  return { files, raw: aggregate(files), filtered, noise, hints: hintsFor(parsed, filtered) }
}
