/**
 * Generator for `src/main/ipc-channels.ts`.
 *
 * The pairing of an IPC channel string to the shape that travels over it is
 * already written down exactly once, in the preload: `settings.patch` is the
 * method whose body invokes `'settings:patch'`. Main never sees that pairing —
 * it registers a handler against a bare string and annotates the arguments
 * by hand, which is how a handler drifts from its caller in silence.
 *
 * So the map is derived from the preload rather than restated. This file reads
 * the `const gt` literal, pairs each leaf's key path with the channel its body
 * invokes, and emits a lookup keyed by channel whose values are read off `GtApi`
 * — the surface the renderer declares and (since `const gt: GtApi`) the preload
 * is bound to. One declaration, three consumers.
 *
 * Run: `bun src/main/ipc-channels.gen.ts`. `src/main/ipc-channels.test.ts`
 * fails if the checked-in output has drifted from a fresh run.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

export type ChannelBinding = {
  /** Dotted key path into `gt`, e.g. `settings.patch`. */
  path: string[]
  /** The channel that key's body invokes, e.g. `settings:patch`. */
  channel: string
}

/** Comments and string bodies carry unbalanced braces — drop them before counting. */
function decommented(line: string): string {
  return line
    .replace(/\/\/.*$/, '')
    .replace(/'(?:[^'\\]|\\.)*'/g, "''")
    .replace(/`(?:[^`\\]|\\.)*`/g, '``')
}

/**
 * Pair every leaf of the `gt` literal with the channel it invokes.
 *
 * Depth-tracked, like the reachability guard's parser: a namespace is a line
 * that is exactly `name: {`, and only lines directly inside the current
 * namespace count as keys — otherwise inline parameter object types read as
 * keys. A leaf spanning several lines is accumulated until the brace depth
 * returns, so a signature broken across lines still finds its invoke.
 *
 * Leaves with no `ipcRenderer.invoke` are skipped: those are the push-event
 * subscriptions (`onFullscreen`, `agents.onStatus`), which carry no request
 * shape and are out of scope for the map.
 */
export function parseBindings(preloadSource: string): ChannelBinding[] {
  const bindings: ChannelBinding[] = []
  const stack: { name: string; depth: number }[] = []
  let depth = 0
  let started = false

  let pending: { path: string[]; text: string; depth: number } | null = null

  const flush = (): void => {
    if (!pending) return
    const invoke = pending.text.match(/ipcRenderer\.invoke\(\s*'([^']+)'/)
    if (invoke) bindings.push({ path: pending.path, channel: invoke[1] })
    pending = null
  }

  for (const raw of preloadSource.split('\n')) {
    const line = decommented(raw)
    if (!started) {
      if (/\bconst gt\b[^=]*= \{/.test(line)) {
        started = true
        depth = 1
      }
      continue
    }

    if (pending) pending.text += `\n${raw}`

    if (depth === 1 + stack.length) {
      const ns = line.match(/^\s*(\w+): \{$/)
      if (ns) {
        flush()
        stack.push({ name: ns[1], depth })
        depth += 1
        continue
      }
      const leaf = line.match(/^\s*(\w+):/)
      if (leaf) {
        flush()
        pending = { path: [...stack.map((s) => s.name), leaf[1]], text: raw, depth }
      }
    }

    const opens = (line.match(/[{(]/g) || []).length
    const closes = (line.match(/[})]/g) || []).length
    depth += opens - closes
    if (pending && depth <= pending.depth - 1) flush()
    while (stack.length && depth <= stack[stack.length - 1].depth) stack.pop()
    if (depth <= 0) break
  }
  flush()
  return bindings
}

const HEADER = `// GENERATED by src/main/ipc-channels.gen.ts — do not edit by hand.
//
// Channel → the argument and result shapes the renderer declares for it, read
// off \`GtApi\` through the preload key that invokes the channel. \`handle\` in
// src/main/typed-ipc.ts binds a main handler to this map, so a handler that
// takes the wrong argument or returns the wrong shape fails the build against
// the caller that will actually make the call.
import type { GtApi } from '../renderer/src/lib/types'

/** The declared args and awaited result of one preload method. */
type Of<F> = F extends (...args: infer A) => infer R ? { args: A; result: Awaited<R> } : never

export type ChannelMap = {
`

/** Emit the module source for `src/main/ipc-channels.ts`. */
export function generateChannelMapSource(preloadSource: string): string {
  const seen = new Map<string, string[]>()
  for (const b of parseBindings(preloadSource)) {
    // First binding wins. Two preload keys onto one channel is legitimate (an
    // alias), and either one describes the same wire shape.
    if (!seen.has(b.channel)) seen.set(b.channel, b.path)
  }
  const rows = [...seen.entries()]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([channel, path]) => {
      const index = path.map((p) => `['${p}']`).join('')
      return `  '${channel}': Of<GtApi${index}>`
    })
  return `${HEADER}${rows.join('\n')}\n}\n`
}

if (import.meta.main) {
  const dir = import.meta.dir
  const source = generateChannelMapSource(readFileSync(join(dir, '..', 'preload', 'index.ts'), 'utf8'))
  writeFileSync(join(dir, 'ipc-channels.ts'), source)
}
